### PR TITLE
Fix some minor annoyances and add stage channel support

### LINKED ISSUE #17: Possible to join Stage Channels?
Hey thanks for this awesome bot... was wondering if maybe you could update the bot to be able to join Stage Channels.

Thanks

### PR DESCRIPTION
**Pull request by AlexIsOK**
Fixed some minor annoyances:
- recordings directory wouldn't auto-create if it didn't exist
- add a catch if there's an issue with the config file (I accidentally used "prefix" instead of "PREFIX" which caused a few minutes of debugging)
- voice channel names were case-sensitive when they shouldn't be

Added stage channel support which fixes #17 (barely had to make changes to it, bot is able to be a listener to the stage channel, though it doesn't play any sounds).

Let me know if you need any changes made to this before merging.

### CODE REVIEW

**Comment by AlexIsOK** [comment]
i haven't tested this with docker so it's possible there could be an issue with that.

**Comment by chebro** [comment]
This looks good to merge! I'll test this out on docker this weekend before merging, thanks for contributing :)

File: index.js [hunk 1]
```diff
@@ -1,9 +1,25 @@
...
+if(!config.PREFIX || !config.BOT_TOKEN) {
+    console.error("Error: the configuration file was configured properly.");
+    console.error("Make sure there are no spelling mistakes.");
+    process.exit(1);
+}
+
+//create the recordings directory in case people forget to do so
+try {
+    fs.mkdirSync("./recordings/");
+} catch(ignored) {}
```
Comment (chebro) [inline index.js:21]: might want to use `path.join(__dirname, recordings)` in case someone runs the script from a different directory and also catch the errors for `EPERM` or `EACCES`, just in case.

File: package.json [hunk 2]
```diff
@@ -14,7 +14,7 @@
 	},
 	"dependencies": {
 		"@discordjs/opus": "^0.3.2",
-		"discord.js": "^12.3.1",
+		"discord.js": "github:discordjs/discord.js#af00ec8970e77ea8a0afd21571eeeef9c554e1ec",
```
Comment (chebro) [inline package.json:17]: Probably have to keep an eye out for the next release so we can change this, everything else looks great!

**Review by chebro — CHANGES_REQUESTED** [review]

**Comment by AlexIsOK** [comment]
it may be easier to remove `recordings` from the root .gitignore file and add a .gitignore to the recordings directory and add `*.pcm`, `*.mp3` and some others to that rather than creating a recordings folder.  this way, there will always be a recordings folder when the user clones it, but audio data from testing won't upload.

**Review by chebro — APPROVED** [review]
